# Generated by Django 3.1.3 on 2020-11-21 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instalacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inst_data', models.DateField(auto_created=True, verbose_name='Data Solic.')),
                ('ins_cliente', models.CharField(max_length=25)),
                ('inst_placa', models.CharField(max_length=7, unique=True)),
                ('ins_contrato', models.CharField(blank=True, max_length=25, null=True)),
                ('inst_solicitante', models.CharField(blank=True, max_length=25, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'instalacao',
            },
        ),
    ]
