# Generated by Django 3.1.3 on 2020-11-24 01:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instaladores', '0002_auto_20201122_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instalacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ins_cliente', models.CharField(max_length=25, verbose_name='Associado')),
                ('inst_placa', models.CharField(max_length=7, unique=True, verbose_name='Placa')),
                ('ins_contrato', models.CharField(blank=True, max_length=25, null=True, verbose_name='Contrato')),
                ('inst_data', models.DateTimeField(auto_now=True, verbose_name='Data da Solicitação')),
                ('inst_data_fim', models.DateField(blank=True, null=True, verbose_name='Data Instalação.')),
                ('inst_obs', models.TextField(blank=True, max_length=300, null=True, verbose_name='Observação')),
                ('inst_instalador', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='instaladores.instaladores')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'instalacao',
            },
        ),
    ]
