# Generated by Django 3.1.3 on 2020-11-21 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instalacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instalacao',
            name='ins_cliente',
            field=models.CharField(max_length=25, verbose_name='Associado'),
        ),
        migrations.AlterField(
            model_name='instalacao',
            name='ins_contrato',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero do contrato'),
        ),
        migrations.AlterField(
            model_name='instalacao',
            name='inst_data',
            field=models.DateField(auto_created=True, verbose_name='Data Solicitação.'),
        ),
        migrations.AlterField(
            model_name='instalacao',
            name='inst_placa',
            field=models.CharField(max_length=7, unique=True, verbose_name='Placa'),
        ),
        migrations.AlterField(
            model_name='instalacao',
            name='inst_solicitante',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Solicitação'),
        ),
    ]
