# Generated by Django 3.1.3 on 2020-11-25 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instalacao', '0005_remove_instalacao_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalacao',
            name='vendedor',
            field=models.CharField(default=1, max_length=25, verbose_name='Vendedor'),
            preserve_default=False,
        ),
    ]
