# Generated by Django 3.1.3 on 2020-11-28 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instalacao', '0008_instalacao_imagens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instalacao',
            name='imagens',
            field=models.FileField(upload_to='%y/%m/%d/'),
        ),
    ]
