<<<<<<< HEAD
# Generated by Django 3.1.3 on 2020-11-22 15:11

from django.db import migrations, models
import django.db.models.deletion
=======
# Generated by Django 3.1.3 on 2020-11-28 16:19

from django.db import migrations, models
>>>>>>> busca


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('endereco', '0001_initial'),
=======
>>>>>>> busca
    ]

    operations = [
        migrations.CreateModel(
            name='Instaladores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('nome', models.CharField(max_length=25)),
                ('cpf', models.CharField(max_length=25, unique=True)),
                ('rg', models.CharField(max_length=25, unique=True)),
                ('tel01', models.CharField(max_length=25)),
                ('tel02', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=4)),
                ('endereco', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='endereco.endereco')),
=======
                ('nome', models.CharField(max_length=60)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('rg', models.CharField(blank=True, max_length=9, null=True)),
                ('endereco', models.CharField(blank=True, max_length=60, null=True)),
                ('numero', models.CharField(blank=True, max_length=4, null=True)),
                ('te01', models.CharField(blank=True, max_length=9, null=True)),
                ('te02', models.CharField(blank=True, max_length=9, null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=4)),
>>>>>>> busca
            ],
            options={
                'db_table': 'instaladores',
            },
        ),
    ]
