# Generated by Django 3.1.3 on 2020-11-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaladores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instaladores',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
