# Generated by Django 3.1.3 on 2020-11-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaladores', '0002_auto_20201128_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='instaladores',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
