# Generated by Django 3.1.3 on 2020-11-28 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instaladores', '0003_instaladores_email'),
        ('instaladores', '0002_auto_20201122_1232'),
    ]

    operations = [
    ]
