# Generated by Django 3.1.3 on 2020-11-13 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prestador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(blank=True, choices=[('MOTO', 'Moto'), ('MECANICA', 'Mecanica'), ('FUNILARIA', 'Funilaria'), ('VIDRO', 'Vidro')], max_length=60, null=True)),
                ('prestador', models.CharField(blank=True, max_length=60, null=True)),
                ('endereco', models.CharField(blank=True, max_length=60, null=True)),
                ('bairro', models.CharField(blank=True, max_length=60, null=True)),
                ('cidade', models.CharField(blank=True, max_length=60, null=True)),
                ('cep', models.CharField(blank=True, max_length=60, null=True)),
                ('telefone2', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'prestador',
            },
        ),
    ]
