# Generated by Django 3.1.3 on 2020-11-18 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscaprest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestador',
            name='telefone1',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
