# Generated by Django 3.1.3 on 2020-11-18 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscaprest', '0002_prestador_telefone1'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestador',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
