# Generated by Django 3.1.3 on 2020-11-14 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rastreadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=60)),
                ('placa', models.CharField(max_length=7, unique=True)),
                ('chassi', models.CharField(max_length=17, unique=True)),
                ('ano_fab', models.CharField(max_length=4)),
                ('modelo', models.CharField(max_length=4)),
                ('renavam', models.CharField(max_length=11)),
                ('cor', models.CharField(choices=[('AZUL', 'AZUL'), ('AMARELO', 'Masculino'), ('BRANCO', 'AMARELO'), ('PRETO', 'PRETO'), ('PRATA', 'PRATA'), ('BEGE', 'BEGE'), ('VERMELHO', 'VERMELHO')], max_length=25)),
                ('rastreador', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rastreadores.rastreador')),
            ],
            options={
                'db_table': 'veiculos',
            },
        ),
    ]
