# Generated by Django 3.1.3 on 2020-11-16 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculos',
            name='cor',
        ),
        migrations.RemoveField(
            model_name='veiculos',
            name='rastreador',
        ),
    ]
