# Generated by Django 3.1.3 on 2020-11-18 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_cliente_veiculo'),
        ('rastreadores', '0001_initial'),
        ('veiculos', '0002_auto_20201115_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculos',
            name='clientes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='veiculos',
            name='rastreador',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rastreadores.rastreador'),
        ),
    ]
