# Generated by Django 3.1.3 on 2020-11-18 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0003_auto_20201117_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculos',
            name='cor',
            field=models.CharField(choices=[('AZUL', 'AZUL'), ('AMARELO', 'Masculino'), ('BRANCO', 'AMARELO'), ('PRETO', 'PRETO'), ('PRATA', 'PRATA'), ('BEGE', 'BEGE'), ('VERMELHO', 'VERMELHO')], default=1, max_length=25),
            preserve_default=False,
        ),
    ]
